# Generated by Django 5.1.3 on 2024-12-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='round_off',
            new_name='round_off_amount',
        ),
    ]
