# Generated by Django 5.1.3 on 2024-12-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_companymaster_invoice_no_prefix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerateSaleInvoice',
        ),
    ]
